Search
AkeenL1/COP4331-Health-Tracking-App pull request #27
Opened 2022-11-12 19:39 UTC by Cryogenic117

2022-11-12 20:21 UTC, Cryogenic117 commented
Also, the changes to the medication screen are just changing <View> to <SafeAreaView> as a quick fix to screens overlapping system display elements on IOS.

2022-11-12 20:59 UTC, conroyr41 requested changes
**Absolutely beautiful!**

I just want to suggest minor changes to the UI.

I think we should add some padding on the far left and far right:

<img src="https://user-images.githubusercontent.com/72236249/201494193-ae217a21-fd88-445e-89b4-528daab50305.png" width="200">

There is too much of a gap here:

<img src="https://user-images.githubusercontent.com/72236249/201494238-b3e0d7c8-2f9f-4904-9e29-a8b61289421e.png" width="200">

Same thing here: There is too much of a gap between the search bar and the results list. 
Also, I think there should be some padding at the very top of the screen:

<img src="https://user-images.githubusercontent.com/72236249/201494300-354e03dc-f853-42d8-988f-c811e7a2e402.png" width="200">

2022-11-13 07:13 UTC, Cryogenic117 commented
All Ready to Go!

2022-11-13 16:38 UTC, conroyr41 approved these changes

2022-11-13 16:38 UTC, merged