Mood and Energy Update 1
AkeenL1/COP4331-Health-Tracking-App pull request #8
Opened 2022-10-21 01:15 UTC by flanneryc

This PR is for the Mood and Energy screen. First update.

2022-10-22 00:46 UTC, conroyr41 requested changes
This code is poorly formatted and does not follow our coding standard. Please make the requested changes.

2022-10-22 00:46 UTC, conroyr41 commented on src/screens/MoodAndEnergy.tsx
> +import React, { useState } from 'react';
You should not have semicolons in your code.

```suggestion
import React, { useState } from 'react'
```

2022-10-22 00:46 UTC, conroyr41 commented on src/screens/MoodAndEnergy.tsx
> +
You have an unnecessary newline here.
```suggestion
```

2022-10-22 00:46 UTC, conroyr41 commented on src/screens/MoodAndEnergy.tsx
> +const styles = StyleSheet.create({
Can we move this constant below the main function for consistency throughout our codebase?

2022-10-22 00:46 UTC, conroyr41 commented on src/screens/MoodAndEnergy.tsx
> +    Button: {
Your styles should be in "camelCase".
```suggestion
    button: {
```

2022-10-22 00:46 UTC, conroyr41 commented on src/screens/MoodAndEnergy.tsx
> +    ]
Why is this variable indented?

2022-10-22 00:46 UTC, conroyr41 commented on src/screens/MoodAndEnergy.tsx
> +    ]
The curly brackets are weirdly indented too.

2022-10-22 00:46 UTC, conroyr41 commented on src/screens/MoodAndEnergy.tsx
> +    }
Same thing here. This entire function is randomly indented.

2022-10-22 00:46 UTC, conroyr41 commented on src/screens/MoodAndEnergy.tsx
> +    }
Please take a look at this return body again. This is not formatted well which makes it unpleasant to read. Please go back over this and add newlines where they are needed and properly indent when necessary. Also, don't forget that it's possible to use a single tag instead of a double tag.

2022-10-22 00:46 UTC, conroyr41 commented on src/screens/MoodAndEnergy.tsx
> +import { View, Text, StyleSheet, TouchableOpacity, Alert} from 'react-native';
There should be a space here.
```suggestion
import { View, Text, StyleSheet, TouchableOpacity, Alert } from 'react-native';
```

2022-10-22 00:54 UTC, conroyr41 commented
This looks very odd to me. Can we make this a horizontal list of emoji buttons like it is in the prototype instead of a weird selection list? You can use Touchable Opacities with nested Text components to achieve this.

<img src="https://user-images.githubusercontent.com/72236249/197308958-bc09f933-bb5f-4c6c-8bff-9a806c76e9f3.png" width="200">

2022-10-22 00:56 UTC, conroyr41 commented
This is a weird way to phrase the question. Can we change this to the same question from the prototype: "How are you feeling today?"?

<img src="https://user-images.githubusercontent.com/72236249/197309219-1cc0db9b-7abb-4538-9269-227dc24f218e.png" width="200">

2022-10-22 00:57 UTC, conroyr41 commented on src/screens/MoodAndEnergy.tsx
> +    }
You can use the other files in the code as a guideline or inspiration.

2022-10-22 00:58 UTC, conroyr41 commented on src/screens/MoodAndEnergy.tsx
> +    }
Also, you should pull main into this branch so that you actually have the latest code.

2022-10-22 01:54 UTC, conroyr41 commented
One more thing, there is a "Notes" button that you guys could import into your screen.

2022-10-25 17:09 UTC, conroyr41 approved these changes

2022-10-25 17:09 UTC, conroyr41 commented
It's still missing the Notes button but it looks good! We'll just worry about the notes button later.

2022-10-26 00:08 UTC, AkeenL1 approved these changes
looks good

2022-10-26 00:13 UTC, merged